# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
