# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 00:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20160813_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='uuid',
            field=models.CharField(max_length=36, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid UUID', regex='^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$')]),
        ),
    ]
