# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_auto_20160813_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
