# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0006_auto_20160817_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='duration',
            field=models.FloatField(),
        ),
    ]
