# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 02:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160918_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='name',
            new_name='object_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='uuid',
        ),
        migrations.AddField(
            model_name='server',
            name='object_key',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36, unique=True, validators=[django.core.validators.RegexValidator(code='invalid object key', message='Invalid object key', regex='^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$')]),
            preserve_default=False,
        ),
    ]
